[drive_ids]
# CSVs
hotels_reviews = "1_jj0vsMuLgN3dZM_5O6bVORe79atnNtt"
review_level_absa = "14KTaN9QALz34X2kdL-ugoKpWGwnXbd6X"
review_aspect_sentiments_long = "1wAB5aHwkC1Fv5DEyEnUqsaaS2JMQ6QCe"
aspect_summary = "1k3ZSYw2aNa1a2D4SKPWOi-XX7wV-F3bR"
sem_aspect_sentence_dataset = "1uNPcTAVbpSbaEk2yzm1mcvldTLDfVNxC"
sem_aspect_sentence_dataset_exploded = "1nCsCtCcZXdSQ-lP6NnvrJHHthH21KJVb"

# Models
lr_sentiment = "12E7OV295o5ScofqF5sSGFGVfRfiFER0s"
sentiment_sentence_student = "1Mm2qtSm3OXOb_-UMo51piJ2gBpnE0kkm"
aspect_detector_ovr = "10GBaDjwQvmSjSv6Q5xJFcM6Zn6p-bmGN"
